import type { DocumentModel } from '../types/document.js';
import { createEmptyDocument } from '../types/document.js';

function id() {
  return crypto.randomUUID();
}

export type TemplateDef = {
  id: string;
  name: string;
  category: 'portada' | 'revista' | 'catalogo' | 'presentacion';
  description: string;
  width: number;
  height: number;
  orientation: 'portrait' | 'landscape';
  build: () => DocumentModel;
};

const FONT = 'Space Grotesk';
const MONO = 'JetBrains Mono';

export const templates: TemplateDef[] = [
  {
    id: 'portada-editorial',
    name: 'Portada editorial',
    category: 'portada',
    description: 'Portada tipográfica con acento neón.',
    width: 1080,
    height: 1350,
    orientation: 'portrait',
    build: () => {
      const doc = createEmptyDocument('Portada editorial', 1080, 1350);
      doc.pages[0].background.fill = '#0B0E11';
      doc.pages[0].elements = [
        {
          id: id(),
          type: 'shape',
          shape: 'rect',
          x: 0,
          y: 0,
          width: 18,
          height: 1350,
          rotation: 0,
          scaleX: 1,
          scaleY: 1,
          opacity: 1,
          zIndex: 0,
          fill: '#4F80FF',
        },
        {
          id: id(),
          type: 'shape',
          shape: 'rect',
          x: 0,
          y: 1020,
          width: 1080,
          height: 330,
          rotation: 0,
          scaleX: 1,
          scaleY: 1,
          opacity: 1,
          zIndex: 1,
          fill: '#4F80FF',
        },
        {
          id: id(),
          type: 'shape',
          shape: 'ellipse',
          x: 620,
          y: 180,
          width: 520,
          height: 520,
          rotation: 0,
          scaleX: 1,
          scaleY: 1,
          opacity: 0.35,
          zIndex: 2,
          fill: '#A855F7',
        },
        {
          id: id(),
          type: 'text',
          x: 72,
          y: 200,
          width: 900,
          height: 160,
          rotation: 0,
          scaleX: 1,
          scaleY: 1,
          opacity: 1,
          zIndex: 3,
          text: 'PLiEGO',
          style: {
            fontSize: 110,
            fontFamily: FONT,
            fontWeight: 700,
            color: '#F4F6F8',
            align: 'left',
            letterSpacing: -2,
          },
        },
        {
          id: id(),
          type: 'text',
          x: 72,
          y: 400,
          width: 720,
          height: 120,
          rotation: 0,
          scaleX: 1,
          scaleY: 1,
          opacity: 1,
          zIndex: 4,
          text: 'Diseño editorial.\nTecnología. Sin límites.',
          style: {
            fontSize: 36,
            fontFamily: FONT,
            fontWeight: 500,
            color: '#8B95A3',
            align: 'left',
            lineHeight: 1.25,
          },
        },
        {
          id: id(),
          type: 'text',
          x: 72,
          y: 1120,
          width: 900,
          height: 50,
          rotation: 0,
          scaleX: 1,
          scaleY: 1,
          opacity: 1,
          zIndex: 5,
          text: 'Nº 01  ·  COLECCIÓN VISUAL',
          style: {
            fontSize: 18,
            fontFamily: MONO,
            fontWeight: 600,
            color: '#0B0E11',
            align: 'left',
            letterSpacing: 3,
          },
        },
      ];
      return doc;
    },
  },
  {
    id: 'revista-doble',
    name: 'Página de revista',
    category: 'revista',
    description: 'Maquetación tipográfica con columna y cita.',
    width: 1200,
    height: 1600,
    orientation: 'portrait',
    build: () => {
      const doc = createEmptyDocument('Revista', 1200, 1600);
      doc.pages[0].background.fill = '#0B0E11';
      doc.pages[0].elements = [
        {
          id: id(),
          type: 'text',
          x: 80,
          y: 90,
          width: 400,
          height: 40,
          rotation: 0,
          scaleX: 1,
          scaleY: 1,
          opacity: 1,
          zIndex: 0,
          text: 'REPORTAJE',
          style: {
            fontSize: 14,
            fontFamily: MONO,
            fontWeight: 600,
            color: '#4F80FF',
            align: 'left',
            letterSpacing: 4,
          },
        },
        {
          id: id(),
          type: 'text',
          x: 80,
          y: 160,
          width: 1000,
          height: 180,
          rotation: 0,
          scaleX: 1,
          scaleY: 1,
          opacity: 1,
          zIndex: 1,
          text: 'La forma como\nsistema editorial',
          style: {
            fontSize: 64,
            fontFamily: FONT,
            fontWeight: 700,
            color: '#F4F6F8',
            align: 'left',
            lineHeight: 1.05,
          },
        },
        {
          id: id(),
          type: 'shape',
          shape: 'rect',
          x: 80,
          y: 420,
          width: 1040,
          height: 420,
          rotation: 0,
          scaleX: 1,
          scaleY: 1,
          opacity: 1,
          zIndex: 2,
          fill: '#161C24',
        },
        {
          id: id(),
          type: 'shape',
          shape: 'rect',
          x: 80,
          y: 420,
          width: 1040,
          height: 8,
          rotation: 0,
          scaleX: 1,
          scaleY: 1,
          opacity: 1,
          zIndex: 3,
          fill: '#FF4EDB',
        },
        {
          id: id(),
          type: 'text',
          x: 80,
          y: 900,
          width: 480,
          height: 400,
          rotation: 0,
          scaleX: 1,
          scaleY: 1,
          opacity: 1,
          zIndex: 4,
          text: 'El diseño gráfico deja de ser ornamentación cuando se convierte en estructura: jerarquía, ritmo, margen y contraste.',
          style: {
            fontSize: 22,
            fontFamily: FONT,
            fontWeight: 400,
            color: '#8B95A3',
            align: 'left',
            lineHeight: 1.45,
          },
        },
        {
          id: id(),
          type: 'text',
          x: 620,
          y: 900,
          width: 500,
          height: 280,
          rotation: 0,
          scaleX: 1,
          scaleY: 1,
          opacity: 1,
          zIndex: 5,
          text: '“Componer es decidir qué debe leerse primero.”',
          style: {
            fontSize: 28,
            fontFamily: FONT,
            fontWeight: 600,
            color: '#F4F6F8',
            align: 'left',
            lineHeight: 1.3,
          },
        },
      ];
      return doc;
    },
  },
  {
    id: 'catalogo-producto',
    name: 'Catálogo de producto',
    category: 'catalogo',
    description: 'Ficha limpia para colecciones y producto.',
    width: 1080,
    height: 1080,
    orientation: 'portrait',
    build: () => {
      const doc = createEmptyDocument('Catálogo', 1080, 1080);
      doc.pages[0].background.fill = '#0B0E11';
      doc.pages[0].elements = [
        {
          id: id(),
          type: 'shape',
          shape: 'rect',
          x: 60,
          y: 60,
          width: 960,
          height: 620,
          rotation: 0,
          scaleX: 1,
          scaleY: 1,
          opacity: 1,
          zIndex: 0,
          fill: '#161C24',
        },
        {
          id: id(),
          type: 'shape',
          shape: 'ellipse',
          x: 280,
          y: 160,
          width: 520,
          height: 420,
          rotation: 0,
          scaleX: 1,
          scaleY: 1,
          opacity: 0.55,
          zIndex: 1,
          fill: '#A855F7',
        },
        {
          id: id(),
          type: 'text',
          x: 60,
          y: 720,
          width: 700,
          height: 80,
          rotation: 0,
          scaleX: 1,
          scaleY: 1,
          opacity: 1,
          zIndex: 2,
          text: 'Colección Norte',
          style: {
            fontSize: 40,
            fontFamily: FONT,
            fontWeight: 700,
            color: '#F4F6F8',
            align: 'left',
          },
        },
        {
          id: id(),
          type: 'text',
          x: 60,
          y: 810,
          width: 700,
          height: 80,
          rotation: 0,
          scaleX: 1,
          scaleY: 1,
          opacity: 1,
          zIndex: 3,
          text: 'Objeto 04  ·  Edición limitada',
          style: {
            fontSize: 18,
            fontFamily: MONO,
            fontWeight: 500,
            color: '#8B95A3',
            align: 'left',
          },
        },
        {
          id: id(),
          type: 'text',
          x: 760,
          y: 730,
          width: 260,
          height: 60,
          rotation: 0,
          scaleX: 1,
          scaleY: 1,
          opacity: 1,
          zIndex: 4,
          text: '128 €',
          style: {
            fontSize: 36,
            fontFamily: FONT,
            fontWeight: 700,
            color: '#B2FF3A',
            align: 'right',
          },
        },
      ];
      return doc;
    },
  },
  {
    id: 'presentacion-slide',
    name: 'Presentación',
    category: 'presentacion',
    description: 'Diapositiva panorámica con título y apoyo.',
    width: 1920,
    height: 1080,
    orientation: 'landscape',
    build: () => {
      const doc = createEmptyDocument('Presentación', 1920, 1080);
      doc.pages[0].background.fill = '#0B0E11';
      doc.pages[0].elements = [
        {
          id: id(),
          type: 'shape',
          shape: 'rect',
          x: 0,
          y: 0,
          width: 18,
          height: 1080,
          rotation: 0,
          scaleX: 1,
          scaleY: 1,
          opacity: 1,
          zIndex: 0,
          fill: '#4F80FF',
        },
        {
          id: id(),
          type: 'shape',
          shape: 'ellipse',
          x: 1280,
          y: -80,
          width: 720,
          height: 720,
          rotation: 0,
          scaleX: 1,
          scaleY: 1,
          opacity: 0.35,
          zIndex: 1,
          fill: '#FF4EDB',
        },
        {
          id: id(),
          type: 'text',
          x: 120,
          y: 320,
          width: 1400,
          height: 160,
          rotation: 0,
          scaleX: 1,
          scaleY: 1,
          opacity: 1,
          zIndex: 2,
          text: 'Sistemas de publicación digital',
          style: {
            fontSize: 72,
            fontFamily: FONT,
            fontWeight: 700,
            color: '#F4F6F8',
            align: 'left',
          },
        },
        {
          id: id(),
          type: 'text',
          x: 120,
          y: 520,
          width: 900,
          height: 80,
          rotation: 0,
          scaleX: 1,
          scaleY: 1,
          opacity: 1,
          zIndex: 3,
          text: 'De la composición gráfica a la arquitectura de producto.',
          style: {
            fontSize: 28,
            fontFamily: FONT,
            fontWeight: 400,
            color: '#8B95A3',
            align: 'left',
          },
        },
      ];
      return doc;
    },
  },
];

export function getTemplate(id: string): TemplateDef | undefined {
  return templates.find((t) => t.id === id);
}
