import type { CanvasElement, DocumentModel, Page } from '../types/document.js';
import { createEmptyDocument } from '../types/document.js';

function id() {
  return crypto.randomUUID();
}

const FONT = 'Space Grotesk';
const MONO = 'JetBrains Mono';
const DISPLAY = 'Syne';
const SERIF = 'Instrument Serif';
const BODY = 'DM Sans';

function base(z: number) {
  return {
    rotation: 0 as const,
    scaleX: 1 as const,
    scaleY: 1 as const,
    opacity: 1,
    zIndex: z,
  };
}

export type TemplateDef = {
  id: string;
  name: string;
  category: 'portada' | 'revista' | 'catalogo' | 'presentacion' | 'editorial';
  description: string;
  width: number;
  height: number;
  orientation: 'portrait' | 'landscape';
  build: () => DocumentModel;
};

function page(
  name: string,
  order: number,
  fill: string,
  elements: CanvasElement[],
): Page {
  return {
    id: id(),
    name,
    order,
    background: { type: 'background', fill },
    elements,
  };
}

/** Multi-page digital magazine cover + story — Readymag energy */
function buildManifestoDigital(): DocumentModel {
  const w = 1440;
  const h = 900;
  const doc = createEmptyDocument('Manifesto digital', w, h);
  doc.pages = [
    page('Portada', 0, '#07090C', [
      {
        id: id(),
        type: 'shape',
        shape: 'ellipse',
        x: 780,
        y: -120,
        width: 820,
        height: 820,
        ...base(0),
        fill: '#4F80FF',
        fillGradient: {
          type: 'radial',
          stops: [
            { offset: 0, color: '#FF4EDB' },
            { offset: 0.45, color: '#A855F7' },
            { offset: 1, color: '#07090C' },
          ],
        },
        opacity: 0.85,
        animation: { preset: 'scaleIn', duration: 1200, trigger: 'load' },
        effects: { blur: 0, blendMode: 'screen' },
      },
      {
        id: id(),
        type: 'text',
        x: 72,
        y: 120,
        width: 420,
        height: 40,
        ...base(1),
        text: 'PLIEGO  ·  VOL. 03',
        style: {
          fontSize: 14,
          fontFamily: MONO,
          fontWeight: 600,
          color: '#4F80FF',
          align: 'left',
          letterSpacing: 4,
          textTransform: 'uppercase',
        },
        animation: { preset: 'fadeIn', delay: 100, trigger: 'load' },
      },
      {
        id: id(),
        type: 'text',
        x: 72,
        y: 220,
        width: 900,
        height: 280,
        ...base(2),
        text: 'LA FORMA\nES EL\nMENSAJE',
        name: 'Display',
        style: {
          fontSize: 118,
          fontFamily: DISPLAY,
          fontWeight: 800,
          color: '#F4F6F8',
          align: 'left',
          lineHeight: 0.9,
          letterSpacing: -4,
          textTransform: 'uppercase',
        },
        animation: { preset: 'fadeUp', duration: 1000, trigger: 'load' },
      },
      {
        id: id(),
        type: 'text',
        x: 72,
        y: 620,
        width: 520,
        height: 100,
        ...base(3),
        text: 'Una publicación digital interactiva.\nScroll, motion y tipografía como dirección de arte.',
        style: {
          fontSize: 20,
          fontFamily: BODY,
          fontWeight: 400,
          color: '#8B95A3',
          align: 'left',
          lineHeight: 1.45,
        },
        animation: { preset: 'fadeUp', delay: 220, trigger: 'load' },
      },
      {
        id: id(),
        type: 'button',
        label: 'Entrar al relato →',
        x: 72,
        y: 760,
        width: 220,
        height: 52,
        ...base(4),
        fill: '#F4F6F8',
        textColor: '#07090C',
        fontFamily: FONT,
        fontSize: 15,
        fontWeight: 600,
        cornerRadius: 999,
        interaction: { href: 'pliego:next', target: '_self', hoverScale: 1.05 },
        animation: { preset: 'fadeUp', delay: 360, trigger: 'load' },
        effects: { shadowBlur: 28, shadowOffsetY: 12, shadowOpacity: 0.35 },
      },
    ]),
    page('Editorial', 1, '#F4F1EA', [
      {
        id: id(),
        type: 'shape',
        shape: 'rect',
        x: 0,
        y: 0,
        width: 480,
        height: 900,
        ...base(0),
        fill: '#0B0E11',
      },
      {
        id: id(),
        type: 'text',
        x: 56,
        y: 80,
        width: 360,
        height: 40,
        ...base(1),
        text: 'ENSAYO',
        style: {
          fontSize: 13,
          fontFamily: MONO,
          fontWeight: 600,
          color: '#4F80FF',
          align: 'left',
          letterSpacing: 5,
        },
        animation: { preset: 'slideRight', trigger: 'scroll' },
      },
      {
        id: id(),
        type: 'text',
        x: 56,
        y: 140,
        width: 380,
        height: 220,
        ...base(2),
        text: 'Diseñar\npara el\nscroll',
        style: {
          fontSize: 64,
          fontFamily: DISPLAY,
          fontWeight: 700,
          color: '#F4F6F8',
          align: 'left',
          lineHeight: 1.02,
          letterSpacing: -2,
        },
        animation: { preset: 'fadeUp', trigger: 'scroll', duration: 900 },
      },
      {
        id: id(),
        type: 'text',
        x: 56,
        y: 420,
        width: 360,
        height: 280,
        ...base(3),
        text: 'El lienzo digital no imita el papel: lo supera. Cada bloque puede entrar, enlazar y respirar. Motion no es adorno — es jerarquía.',
        style: {
          fontSize: 18,
          fontFamily: BODY,
          fontWeight: 400,
          color: '#8B95A3',
          align: 'left',
          lineHeight: 1.55,
        },
        animation: { preset: 'fadeIn', delay: 120, trigger: 'scroll' },
      },
      {
        id: id(),
        type: 'text',
        x: 560,
        y: 120,
        width: 780,
        height: 200,
        ...base(4),
        text: '“Una página memorable no se lee: se habita.”',
        style: {
          fontSize: 48,
          fontFamily: SERIF,
          fontWeight: 400,
          color: '#111111',
          align: 'left',
          lineHeight: 1.2,
          italic: true,
        },
        animation: { preset: 'blurIn', trigger: 'scroll', duration: 1100 },
      },
      {
        id: id(),
        type: 'shape',
        shape: 'rect',
        x: 560,
        y: 360,
        width: 120,
        height: 4,
        ...base(5),
        fill: '#FF4EDB',
        animation: { preset: 'slideLeft', trigger: 'scroll' },
      },
      {
        id: id(),
        type: 'text',
        x: 560,
        y: 400,
        width: 720,
        height: 320,
        ...base(6),
        text: 'Usa tipografía display para el golpe visual, serif para la voz editorial y mono para metadatos. Combina CTAs, vídeo y gradientes como capas de dirección de arte — no como widgets genéricos.\n\nPublica. Comparte. Itera. El producto final debe sentir estudio creativo, no plantilla de presentación.',
        style: {
          fontSize: 20,
          fontFamily: BODY,
          fontWeight: 400,
          color: '#2A2F36',
          align: 'left',
          lineHeight: 1.55,
        },
        animation: { preset: 'fadeUp', delay: 160, trigger: 'scroll' },
      },
    ]),
    page('Cierre', 2, '#0B0E11', [
      {
        id: id(),
        type: 'shape',
        shape: 'rect',
        x: 0,
        y: 0,
        width: 1440,
        height: 900,
        ...base(0),
        fill: '#0B0E11',
        fillGradient: {
          type: 'linear',
          angle: 160,
          stops: [
            { offset: 0, color: '#0B0E11' },
            { offset: 0.55, color: '#121826' },
            { offset: 1, color: '#1a1030' },
          ],
        },
      },
      {
        id: id(),
        type: 'shape',
        shape: 'ellipse',
        x: 480,
        y: 120,
        width: 480,
        height: 480,
        ...base(1),
        fill: '#4F80FF',
        fillGradient: {
          type: 'radial',
          stops: [
            { offset: 0, color: '#FF4EDB' },
            { offset: 0.5, color: '#4F80FF' },
            { offset: 1, color: '#0B0E11' },
          ],
        },
        opacity: 0.45,
        animation: { preset: 'scaleIn', trigger: 'scroll', duration: 1200 },
        effects: { blendMode: 'screen' },
      },
      {
        id: id(),
        type: 'text',
        x: 120,
        y: 260,
        width: 1200,
        height: 180,
        ...base(2),
        text: 'HAZ ALGO\nIMPOSIBLE DE IGNORAR',
        style: {
          fontSize: 72,
          fontFamily: DISPLAY,
          fontWeight: 800,
          color: '#F4F6F8',
          align: 'center',
          lineHeight: 0.95,
          letterSpacing: -2,
        },
        animation: { preset: 'scaleIn', trigger: 'scroll', duration: 1000 },
      },
      {
        id: id(),
        type: 'text',
        x: 320,
        y: 480,
        width: 800,
        height: 40,
        ...base(3),
        text: 'Publica el manifiesto. Comparte el link. Itera en vivo.',
        style: {
          fontSize: 18,
          fontFamily: BODY,
          fontWeight: 400,
          color: '#8B95A3',
          align: 'center',
        },
        animation: { preset: 'fadeUp', delay: 120, trigger: 'scroll' },
      },
      {
        id: id(),
        type: 'button',
        label: 'Publicar con PLIEGO',
        x: 520,
        y: 560,
        width: 400,
        height: 56,
        ...base(4),
        fill: '#B2FF3A',
        textColor: '#0B0E11',
        fontFamily: FONT,
        fontSize: 16,
        fontWeight: 700,
        cornerRadius: 999,
        interaction: { href: 'pliego:next', hoverScale: 1.06 },
        animation: { preset: 'fadeUp', delay: 200, trigger: 'scroll' },
        effects: {
          shadowBlur: 36,
          shadowOffsetY: 14,
          shadowOpacity: 0.4,
        },
      },
      {
        id: id(),
        type: 'text',
        x: 420,
        y: 660,
        width: 600,
        height: 32,
        ...base(5),
        text: 'PLIEGO  ·  editorial digital interactiva',
        style: {
          fontSize: 13,
          fontFamily: MONO,
          fontWeight: 500,
          color: '#8B95A3',
          align: 'center',
          letterSpacing: 2,
        },
        animation: { preset: 'fadeIn', delay: 280, trigger: 'scroll' },
      },
    ]),
  ];
  doc.meta.width = w;
  doc.meta.height = h;
  doc.meta.templateId = 'manifesto-digital';
  doc.meta.templateName = 'Manifiesto digital';
  return doc;
}

function buildPortfolioKinetic(): DocumentModel {
  const w = 1080;
  const h = 1350;
  const doc = createEmptyDocument('Portfolio kinetic', w, h);
  doc.pages = [
    page('Hero', 0, '#050608', [
      {
        id: id(),
        type: 'shape',
        shape: 'ellipse',
        x: 520,
        y: -180,
        width: 780,
        height: 780,
        ...base(0),
        fill: '#4F80FF',
        fillGradient: {
          type: 'radial',
          stops: [
            { offset: 0, color: '#4F80FF' },
            { offset: 0.4, color: '#A855F7' },
            { offset: 1, color: '#050608' },
          ],
        },
        opacity: 0.75,
        animation: { preset: 'scaleIn', duration: 1400, trigger: 'load' },
        effects: { blendMode: 'screen' },
      },
      {
        id: id(),
        type: 'shape',
        shape: 'ellipse',
        x: -220,
        y: 820,
        width: 560,
        height: 560,
        ...base(1),
        fill: '#FF4EDB',
        fillGradient: {
          type: 'radial',
          stops: [
            { offset: 0, color: '#FF4EDB' },
            { offset: 1, color: '#050608' },
          ],
        },
        opacity: 0.45,
        animation: { preset: 'fadeIn', delay: 200, trigger: 'load' },
      },
      {
        id: id(),
        type: 'text',
        x: 64,
        y: 88,
        width: 520,
        height: 36,
        ...base(2),
        text: 'STUDIO  ·  2026  ·  SELECTED WORK',
        style: {
          fontSize: 14,
          fontFamily: MONO,
          fontWeight: 600,
          color: '#8B95A3',
          align: 'left',
          letterSpacing: 3,
        },
        animation: { preset: 'fadeIn', trigger: 'load' },
      },
      {
        id: id(),
        type: 'text',
        x: 64,
        y: 200,
        width: 950,
        height: 420,
        ...base(3),
        text: 'Trabajos\nque se\nsienten',
        style: {
          fontSize: 118,
          fontFamily: DISPLAY,
          fontWeight: 800,
          color: '#F4F6F8',
          align: 'left',
          lineHeight: 0.9,
          letterSpacing: -5,
        },
        animation: { preset: 'fadeUp', duration: 1100, trigger: 'load' },
      },
      {
        id: id(),
        type: 'shape',
        shape: 'rect',
        x: 64,
        y: 680,
        width: 72,
        height: 4,
        ...base(4),
        fill: '#B2FF3A',
        animation: { preset: 'slideLeft', delay: 180, trigger: 'load' },
      },
      {
        id: id(),
        type: 'text',
        x: 64,
        y: 720,
        width: 720,
        height: 100,
        ...base(5),
        text: 'Dirección de arte · Editorial digital · Identidad\nMotion y tipografía como producto.',
        style: {
          fontSize: 20,
          fontFamily: BODY,
          fontWeight: 400,
          color: '#B8C0CC',
          align: 'left',
          lineHeight: 1.45,
        },
        animation: { preset: 'fadeUp', delay: 220, trigger: 'load' },
      },
      {
        id: id(),
        type: 'button',
        label: 'Ver casos →',
        x: 64,
        y: 1180,
        width: 200,
        height: 52,
        ...base(6),
        fill: '#F4F6F8',
        textColor: '#050608',
        cornerRadius: 999,
        fontSize: 15,
        fontWeight: 600,
        fontFamily: FONT,
        interaction: { href: 'pliego:next', hoverScale: 1.05 },
        animation: { preset: 'fadeUp', delay: 320, trigger: 'load' },
        effects: { shadowBlur: 28, shadowOffsetY: 12, shadowOpacity: 0.35 },
      },
      {
        id: id(),
        type: 'shape',
        shape: 'rect',
        x: 0,
        y: 1288,
        width: 1080,
        height: 62,
        ...base(7),
        fill: '#4F80FF',
        fillGradient: {
          type: 'linear',
          angle: 90,
          stops: [
            { offset: 0, color: '#4F80FF' },
            { offset: 0.5, color: '#A855F7' },
            { offset: 1, color: '#FF4EDB' },
          ],
        },
      },
    ]),
    page('Case', 1, '#0B0E11', [
      {
        id: id(),
        type: 'text',
        x: 64,
        y: 72,
        width: 480,
        height: 32,
        ...base(0),
        text: '01  —  CASE STUDY',
        style: {
          fontSize: 13,
          fontFamily: MONO,
          fontWeight: 600,
          color: '#B2FF3A',
          align: 'left',
          letterSpacing: 3,
        },
        animation: { preset: 'fadeIn', trigger: 'scroll' },
      },
      {
        id: id(),
        type: 'text',
        x: 64,
        y: 130,
        width: 950,
        height: 180,
        ...base(1),
        text: 'Revista líquida\npara una marca cultural',
        style: {
          fontSize: 54,
          fontFamily: DISPLAY,
          fontWeight: 800,
          color: '#F4F6F8',
          align: 'left',
          lineHeight: 1.05,
          letterSpacing: -2,
        },
        animation: { preset: 'fadeUp', trigger: 'scroll' },
      },
      {
        id: id(),
        type: 'shape',
        shape: 'rect',
        x: 64,
        y: 360,
        width: 952,
        height: 420,
        ...base(2),
        fill: '#121826',
        cornerRadius: 16,
        fillGradient: {
          type: 'linear',
          angle: 145,
          stops: [
            { offset: 0, color: '#152238' },
            { offset: 0.55, color: '#4F80FF' },
            { offset: 1, color: '#FF4EDB' },
          ],
        },
        animation: { preset: 'scaleIn', trigger: 'scroll', duration: 900 },
        effects: { shadowBlur: 48, shadowOffsetY: 24, shadowOpacity: 0.35 },
      },
      {
        id: id(),
        type: 'text',
        x: 100,
        y: 500,
        width: 860,
        height: 140,
        ...base(3),
        text: 'Imagen · vídeo · tipografía\nen un solo scroll narrativo',
        style: {
          fontSize: 36,
          fontFamily: FONT,
          fontWeight: 600,
          color: '#F4F6F8',
          align: 'left',
          lineHeight: 1.2,
        },
        animation: { preset: 'fadeUp', delay: 160, trigger: 'scroll' },
      },
      {
        id: id(),
        type: 'text',
        x: 64,
        y: 840,
        width: 920,
        height: 220,
        ...base(4),
        text: 'Sustituye este bloque por tu fotografía o vídeo. Ajusta motion en el inspector: fade, scale, blur. Enlaza el CTA a tu estudio o a la siguiente página publicada.\n\nTres capas. Una historia. Cero plantilla genérica.',
        style: {
          fontSize: 18,
          fontFamily: BODY,
          fontWeight: 400,
          color: '#8B95A3',
          align: 'left',
          lineHeight: 1.55,
        },
        animation: { preset: 'fadeIn', delay: 100, trigger: 'scroll' },
      },
      {
        id: id(),
        type: 'button',
        label: 'Siguiente →',
        x: 64,
        y: 1180,
        width: 180,
        height: 48,
        ...base(5),
        fill: '#B2FF3A',
        textColor: '#050608',
        cornerRadius: 999,
        fontSize: 14,
        fontWeight: 700,
        interaction: { href: 'pliego:next', hoverScale: 1.05 },
        animation: { preset: 'fadeUp', trigger: 'scroll' },
      },
    ]),
    page('Cierre', 2, '#050608', [
      {
        id: id(),
        type: 'shape',
        shape: 'ellipse',
        x: 200,
        y: 200,
        width: 680,
        height: 680,
        ...base(0),
        fill: '#A855F7',
        fillGradient: {
          type: 'radial',
          stops: [
            { offset: 0, color: '#FF4EDB' },
            { offset: 0.5, color: '#A855F7' },
            { offset: 1, color: '#050608' },
          ],
        },
        opacity: 0.55,
        animation: { preset: 'scaleIn', trigger: 'scroll', duration: 1200 },
      },
      {
        id: id(),
        type: 'text',
        x: 80,
        y: 420,
        width: 920,
        height: 200,
        ...base(1),
        text: 'HAZ ALGO\nIMPOSIBLE\nDE IGNORAR',
        style: {
          fontSize: 72,
          fontFamily: DISPLAY,
          fontWeight: 800,
          color: '#F4F6F8',
          align: 'center',
          lineHeight: 0.92,
          letterSpacing: -2,
        },
        animation: { preset: 'fadeUp', trigger: 'scroll', duration: 1000 },
      },
      {
        id: id(),
        type: 'button',
        label: 'Publicar con PLIEGO',
        x: 340,
        y: 720,
        width: 400,
        height: 56,
        ...base(2),
        fill: '#F4F6F8',
        textColor: '#050608',
        cornerRadius: 999,
        fontSize: 16,
        fontWeight: 700,
        fontFamily: FONT,
        interaction: { href: 'pliego:next', hoverScale: 1.06 },
        animation: { preset: 'fadeUp', delay: 180, trigger: 'scroll' },
        effects: { shadowBlur: 32, shadowOffsetY: 14, shadowOpacity: 0.4 },
      },
      {
        id: id(),
        type: 'text',
        x: 240,
        y: 820,
        width: 600,
        height: 40,
        ...base(3),
        text: 'Abre el estudio · elige formato · publica',
        style: {
          fontSize: 14,
          fontFamily: MONO,
          fontWeight: 500,
          color: '#8B95A3',
          align: 'center',
          letterSpacing: 2,
        },
        animation: { preset: 'fadeIn', delay: 280, trigger: 'scroll' },
      },
    ]),
  ];
  doc.meta.width = w;
  doc.meta.height = h;
  doc.meta.templateId = 'portfolio-kinetic';
  doc.meta.templateName = 'Portfolio kinetic';
  return doc;
}

function buildPortadaEditorial(): DocumentModel {
  const w = 1080;
  const h = 1350;
  const doc = createEmptyDocument('Portada editorial', w, h);
  doc.pages = [
    page('Portada', 0, '#050608', [
      {
        id: id(),
        type: 'shape',
        shape: 'ellipse',
        x: 420,
        y: -200,
        width: 900,
        height: 900,
        ...base(0),
        fill: '#A855F7',
        fillGradient: {
          type: 'radial',
          stops: [
            { offset: 0, color: '#FF4EDB' },
            { offset: 0.35, color: '#A855F7' },
            { offset: 0.7, color: '#4F80FF' },
            { offset: 1, color: '#050608' },
          ],
        },
        opacity: 0.9,
        animation: { preset: 'scaleIn', duration: 1400, trigger: 'load' },
        effects: { blendMode: 'screen' },
      },
      {
        id: id(),
        type: 'shape',
        shape: 'rect',
        x: 0,
        y: 0,
        width: 18,
        height: h,
        ...base(1),
        fill: '#4F80FF',
        fillGradient: {
          type: 'linear',
          angle: 180,
          stops: [
            { offset: 0, color: '#4F80FF' },
            { offset: 0.5, color: '#FF4EDB' },
            { offset: 1, color: '#B2FF3A' },
          ],
        },
      },
      {
        id: id(),
        type: 'text',
        x: 72,
        y: 72,
        width: 400,
        height: 32,
        ...base(2),
        text: 'PLIEGO  ·  VOL. 01  ·  COVER',
        style: {
          fontSize: 13,
          fontFamily: MONO,
          fontWeight: 600,
          color: '#8B95A3',
          align: 'left',
          letterSpacing: 3,
        },
        animation: { preset: 'fadeIn', trigger: 'load' },
      },
      {
        id: id(),
        type: 'text',
        x: 72,
        y: 360,
        width: 920,
        height: 280,
        ...base(3),
        text: 'PLiEGO',
        style: {
          fontSize: 148,
          fontFamily: DISPLAY,
          fontWeight: 800,
          color: '#F4F6F8',
          align: 'left',
          letterSpacing: -6,
          lineHeight: 0.9,
        },
        animation: { preset: 'fadeUp', duration: 1000, trigger: 'load' },
      },
      {
        id: id(),
        type: 'shape',
        shape: 'rect',
        x: 72,
        y: 640,
        width: 80,
        height: 5,
        ...base(4),
        fill: '#B2FF3A',
        animation: { preset: 'slideLeft', delay: 160, trigger: 'load' },
      },
      {
        id: id(),
        type: 'text',
        x: 72,
        y: 680,
        width: 720,
        height: 100,
        ...base(5),
        text: 'Diseño editorial.\nTecnología. Sin límites.',
        style: {
          fontSize: 28,
          fontFamily: FONT,
          fontWeight: 500,
          color: '#F4F6F8',
          align: 'left',
          lineHeight: 1.25,
        },
        animation: { preset: 'fadeUp', delay: 220, trigger: 'load' },
      },
      {
        id: id(),
        type: 'button',
        label: 'Abrir el número →',
        x: 72,
        y: 1180,
        width: 240,
        height: 52,
        ...base(6),
        fill: '#F4F6F8',
        textColor: '#050608',
        cornerRadius: 999,
        fontSize: 15,
        fontWeight: 700,
        fontFamily: FONT,
        interaction: { href: 'pliego:next', hoverScale: 1.05 },
        animation: { preset: 'fadeUp', delay: 320, trigger: 'load' },
        effects: { shadowBlur: 28, shadowOffsetY: 12, shadowOpacity: 0.35 },
      },
    ]),
    page('Editorial', 1, '#0B0E11', [
      {
        id: id(),
        type: 'shape',
        shape: 'rect',
        x: 0,
        y: 0,
        width: 1080,
        height: 420,
        ...base(0),
        fill: '#121826',
        fillGradient: {
          type: 'linear',
          angle: 160,
          stops: [
            { offset: 0, color: '#152238' },
            { offset: 0.6, color: '#4F80FF' },
            { offset: 1, color: '#FF4EDB' },
          ],
        },
      },
      {
        id: id(),
        type: 'text',
        x: 72,
        y: 72,
        width: 400,
        height: 32,
        ...base(1),
        text: '02  —  CUERPO EDITORIAL',
        style: {
          fontSize: 13,
          fontFamily: MONO,
          fontWeight: 600,
          color: '#B2FF3A',
          align: 'left',
          letterSpacing: 3,
        },
        animation: { preset: 'fadeIn', trigger: 'scroll' },
      },
      {
        id: id(),
        type: 'text',
        x: 72,
        y: 140,
        width: 900,
        height: 180,
        ...base(2),
        text: 'Una portada\nque se navega',
        style: {
          fontSize: 64,
          fontFamily: DISPLAY,
          fontWeight: 800,
          color: '#F4F6F8',
          align: 'left',
          lineHeight: 1.02,
          letterSpacing: -2,
        },
        animation: { preset: 'fadeUp', trigger: 'scroll' },
      },
      {
        id: id(),
        type: 'text',
        x: 72,
        y: 480,
        width: 920,
        height: 280,
        ...base(3),
        text: 'Sustituye el bloque superior por tu fotografía o vídeo. Usa tipografía display para el golpe, mono para metadatos y un CTA que lleve al siguiente capítulo.\n\nMotion al scroll = jerarquía. Enlaces = narrativa. PLIEGO no imprime una portada: la publica viva.',
        style: {
          fontSize: 20,
          fontFamily: BODY,
          fontWeight: 400,
          color: '#B8C0CC',
          align: 'left',
          lineHeight: 1.55,
        },
        animation: { preset: 'fadeIn', delay: 120, trigger: 'scroll' },
      },
      {
        id: id(),
        type: 'shape',
        shape: 'rect',
        x: 72,
        y: 820,
        width: 280,
        height: 200,
        ...base(4),
        fill: '#121826',
        cornerRadius: 12,
        stroke: 'rgba(79,128,255,0.4)',
        strokeWidth: 1,
        animation: { preset: 'fadeUp', trigger: 'scroll' },
      },
      {
        id: id(),
        type: 'text',
        x: 96,
        y: 860,
        width: 230,
        height: 120,
        ...base(5),
        text: 'Tipografía\ncomo\ndirección',
        style: {
          fontSize: 22,
          fontFamily: FONT,
          fontWeight: 600,
          color: '#F4F6F8',
          align: 'left',
          lineHeight: 1.2,
        },
        animation: { preset: 'fadeUp', delay: 80, trigger: 'scroll' },
      },
      {
        id: id(),
        type: 'shape',
        shape: 'rect',
        x: 400,
        y: 820,
        width: 280,
        height: 200,
        ...base(6),
        fill: '#121826',
        cornerRadius: 12,
        stroke: 'rgba(255,78,219,0.35)',
        strokeWidth: 1,
        animation: { preset: 'fadeUp', delay: 100, trigger: 'scroll' },
      },
      {
        id: id(),
        type: 'text',
        x: 424,
        y: 860,
        width: 230,
        height: 120,
        ...base(7),
        text: 'Motion\ncomo\njerarquía',
        style: {
          fontSize: 22,
          fontFamily: FONT,
          fontWeight: 600,
          color: '#F4F6F8',
          align: 'left',
          lineHeight: 1.2,
        },
        animation: { preset: 'fadeUp', delay: 140, trigger: 'scroll' },
      },
      {
        id: id(),
        type: 'shape',
        shape: 'rect',
        x: 728,
        y: 820,
        width: 280,
        height: 200,
        ...base(8),
        fill: '#121826',
        cornerRadius: 12,
        stroke: 'rgba(178,255,58,0.35)',
        strokeWidth: 1,
        animation: { preset: 'fadeUp', delay: 160, trigger: 'scroll' },
      },
      {
        id: id(),
        type: 'text',
        x: 752,
        y: 860,
        width: 230,
        height: 120,
        ...base(9),
        text: 'CTA\ncomo\nnarrativa',
        style: {
          fontSize: 22,
          fontFamily: FONT,
          fontWeight: 600,
          color: '#F4F6F8',
          align: 'left',
          lineHeight: 1.2,
        },
        animation: { preset: 'fadeUp', delay: 200, trigger: 'scroll' },
      },
      {
        id: id(),
        type: 'button',
        label: 'Ir al cierre →',
        x: 72,
        y: 1180,
        width: 200,
        height: 48,
        ...base(10),
        fill: '#4F80FF',
        textColor: '#FFFFFF',
        cornerRadius: 999,
        fontSize: 14,
        fontWeight: 600,
        interaction: { href: 'pliego:next', hoverScale: 1.05 },
        animation: { preset: 'fadeUp', trigger: 'scroll' },
      },
    ]),
    page('Cierre', 2, '#050608', [
      {
        id: id(),
        type: 'shape',
        shape: 'ellipse',
        x: 180,
        y: 260,
        width: 720,
        height: 720,
        ...base(0),
        fill: '#4F80FF',
        fillGradient: {
          type: 'radial',
          stops: [
            { offset: 0, color: '#B2FF3A' },
            { offset: 0.4, color: '#4F80FF' },
            { offset: 1, color: '#050608' },
          ],
        },
        opacity: 0.5,
        animation: { preset: 'scaleIn', trigger: 'scroll', duration: 1200 },
      },
      {
        id: id(),
        type: 'text',
        x: 80,
        y: 400,
        width: 920,
        height: 220,
        ...base(1),
        text: 'PUBLICA.\nCOMPARTE.\nITERA.',
        style: {
          fontSize: 72,
          fontFamily: DISPLAY,
          fontWeight: 800,
          color: '#F4F6F8',
          align: 'center',
          lineHeight: 0.95,
          letterSpacing: -2,
        },
        animation: { preset: 'fadeUp', trigger: 'scroll', duration: 1000 },
      },
      {
        id: id(),
        type: 'button',
        label: 'Publicar con PLIEGO',
        x: 300,
        y: 720,
        width: 480,
        height: 56,
        ...base(2),
        fill: '#B2FF3A',
        textColor: '#050608',
        cornerRadius: 999,
        fontSize: 16,
        fontWeight: 700,
        fontFamily: FONT,
        interaction: { href: 'pliego:next', hoverScale: 1.06 },
        animation: { preset: 'fadeUp', delay: 180, trigger: 'scroll' },
        effects: { shadowBlur: 32, shadowOffsetY: 14, shadowOpacity: 0.4 },
      },
      {
        id: id(),
        type: 'text',
        x: 240,
        y: 820,
        width: 600,
        height: 40,
        ...base(3),
        text: 'Tu portada ya no es estática',
        style: {
          fontSize: 14,
          fontFamily: MONO,
          fontWeight: 500,
          color: '#8B95A3',
          align: 'center',
          letterSpacing: 2,
        },
        animation: { preset: 'fadeIn', delay: 260, trigger: 'scroll' },
      },
    ]),
  ];
  doc.meta.width = w;
  doc.meta.height = h;
  doc.meta.templateId = 'portada-editorial';
  doc.meta.templateName = 'Portada editorial';
  return doc;
}

function buildRevista(): DocumentModel {
  const w = 1200;
  const h = 1600;
  const doc = createEmptyDocument('Revista', w, h);
  doc.pages = [
    page('Portada', 0, '#050608', [
      {
        id: id(),
        type: 'shape',
        shape: 'rect',
        x: 0,
        y: 0,
        width: w,
        height: 520,
        ...base(0),
        fill: '#121826',
        fillGradient: {
          type: 'linear',
          angle: 125,
          stops: [
            { offset: 0, color: '#0B0E11' },
            { offset: 0.45, color: '#4F80FF' },
            { offset: 1, color: '#FF4EDB' },
          ],
        },
      },
      {
        id: id(),
        type: 'text',
        x: 80,
        y: 80,
        width: 400,
        height: 36,
        ...base(1),
        text: 'REPORTAJE  ·  N.º 07',
        style: {
          fontSize: 14,
          fontFamily: MONO,
          fontWeight: 600,
          color: '#F4F6F8',
          align: 'left',
          letterSpacing: 4,
        },
        animation: { preset: 'fadeIn', trigger: 'load' },
      },
      {
        id: id(),
        type: 'text',
        x: 80,
        y: 180,
        width: 1040,
        height: 240,
        ...base(2),
        text: 'La forma como\nsistema editorial',
        style: {
          fontSize: 72,
          fontFamily: DISPLAY,
          fontWeight: 800,
          color: '#F4F6F8',
          align: 'left',
          lineHeight: 1.0,
          letterSpacing: -2,
        },
        animation: { preset: 'fadeUp', trigger: 'load' },
      },
      {
        id: id(),
        type: 'text',
        x: 80,
        y: 580,
        width: 900,
        height: 80,
        ...base(3),
        text: 'Tipografía, ritmo y contraste en un scroll que se siente revista viva.',
        style: {
          fontSize: 22,
          fontFamily: BODY,
          fontWeight: 400,
          color: '#B8C0CC',
          align: 'left',
          lineHeight: 1.45,
        },
        animation: { preset: 'fadeUp', delay: 160, trigger: 'load' },
      },
      {
        id: id(),
        type: 'shape',
        shape: 'rect',
        x: 80,
        y: 720,
        width: 1040,
        height: 560,
        ...base(4),
        fill: '#151a22',
        cornerRadius: 8,
        fillGradient: {
          type: 'linear',
          angle: 140,
          stops: [
            { offset: 0, color: '#151a22' },
            { offset: 0.5, color: '#2a1850' },
            { offset: 1, color: '#4F80FF' },
          ],
        },
        animation: { preset: 'scaleIn', trigger: 'load', duration: 1000 },
        effects: { shadowBlur: 40, shadowOffsetY: 20, shadowOpacity: 0.4 },
      },
      {
        id: id(),
        type: 'text',
        x: 120,
        y: 940,
        width: 960,
        height: 120,
        ...base(5),
        text: 'Sustituye este bloque\npor imagen o vídeo',
        style: {
          fontSize: 40,
          fontFamily: FONT,
          fontWeight: 600,
          color: '#F4F6F8',
          align: 'left',
          lineHeight: 1.15,
        },
        animation: { preset: 'fadeUp', delay: 220, trigger: 'load' },
      },
      {
        id: id(),
        type: 'button',
        label: 'Leer el reportaje →',
        x: 80,
        y: 1440,
        width: 260,
        height: 52,
        ...base(6),
        fill: '#F4F6F8',
        textColor: '#050608',
        cornerRadius: 999,
        fontSize: 15,
        fontWeight: 700,
        fontFamily: FONT,
        interaction: { href: 'pliego:next', hoverScale: 1.05 },
        animation: { preset: 'fadeUp', delay: 300, trigger: 'load' },
      },
    ]),
    page('Cuerpo', 1, '#F4F1EA', [
      {
        id: id(),
        type: 'shape',
        shape: 'rect',
        x: 0,
        y: 0,
        width: 420,
        height: h,
        ...base(0),
        fill: '#0B0E11',
      },
      {
        id: id(),
        type: 'text',
        x: 56,
        y: 80,
        width: 300,
        height: 32,
        ...base(1),
        text: 'ENSAYO',
        style: {
          fontSize: 13,
          fontFamily: MONO,
          fontWeight: 600,
          color: '#4F80FF',
          align: 'left',
          letterSpacing: 5,
        },
        animation: { preset: 'slideRight', trigger: 'scroll' },
      },
      {
        id: id(),
        type: 'text',
        x: 56,
        y: 150,
        width: 320,
        height: 280,
        ...base(2),
        text: 'Diseñar\npara el\nscroll',
        style: {
          fontSize: 56,
          fontFamily: DISPLAY,
          fontWeight: 800,
          color: '#F4F6F8',
          align: 'left',
          lineHeight: 1.05,
          letterSpacing: -2,
        },
        animation: { preset: 'fadeUp', trigger: 'scroll' },
      },
      {
        id: id(),
        type: 'text',
        x: 56,
        y: 500,
        width: 300,
        height: 320,
        ...base(3),
        text: 'Cada columna puede entrar, enlazar y respirar. Motion no es adorno — es ritmo editorial.',
        style: {
          fontSize: 18,
          fontFamily: BODY,
          fontWeight: 400,
          color: '#8B95A3',
          align: 'left',
          lineHeight: 1.55,
        },
        animation: { preset: 'fadeIn', delay: 100, trigger: 'scroll' },
      },
      {
        id: id(),
        type: 'text',
        x: 500,
        y: 120,
        width: 620,
        height: 200,
        ...base(4),
        text: '“Una página memorable no se lee: se habita.”',
        style: {
          fontSize: 42,
          fontFamily: SERIF,
          fontWeight: 400,
          color: '#111111',
          align: 'left',
          lineHeight: 1.25,
          italic: true,
        },
        animation: { preset: 'blurIn', trigger: 'scroll', duration: 1100 },
      },
      {
        id: id(),
        type: 'shape',
        shape: 'rect',
        x: 500,
        y: 360,
        width: 100,
        height: 4,
        ...base(5),
        fill: '#FF4EDB',
        animation: { preset: 'slideLeft', trigger: 'scroll' },
      },
      {
        id: id(),
        type: 'text',
        x: 500,
        y: 420,
        width: 620,
        height: 480,
        ...base(6),
        text: 'Combina display para el golpe visual, serif para la voz editorial y mono para metadatos. Activa motion al scroll, enlaza CTAs a la siguiente página y publica una experiencia que se sienta estudio creativo — no un PDF plano.\n\nSustituye este texto. Ajusta tipografía. Publica.',
        style: {
          fontSize: 20,
          fontFamily: BODY,
          fontWeight: 400,
          color: '#2A2F36',
          align: 'left',
          lineHeight: 1.55,
        },
        animation: { preset: 'fadeUp', delay: 140, trigger: 'scroll' },
      },
      {
        id: id(),
        type: 'button',
        label: 'Al cierre →',
        x: 500,
        y: 1440,
        width: 180,
        height: 48,
        ...base(7),
        fill: '#0B0E11',
        textColor: '#F4F6F8',
        cornerRadius: 999,
        fontSize: 14,
        fontWeight: 600,
        interaction: { href: 'pliego:next', hoverScale: 1.05 },
        animation: { preset: 'fadeUp', trigger: 'scroll' },
      },
    ]),
    page('Cierre', 2, '#050608', [
      {
        id: id(),
        type: 'shape',
        shape: 'rect',
        x: 0,
        y: 0,
        width: w,
        height: h,
        ...base(0),
        fill: '#050608',
        fillGradient: {
          type: 'linear',
          angle: 160,
          stops: [
            { offset: 0, color: '#050608' },
            { offset: 0.5, color: '#121826' },
            { offset: 1, color: '#1a1030' },
          ],
        },
      },
      {
        id: id(),
        type: 'text',
        x: 80,
        y: 480,
        width: 1040,
        height: 200,
        ...base(1),
        text: 'HAZ ALGO\nIMPOSIBLE DE IGNORAR',
        style: {
          fontSize: 64,
          fontFamily: DISPLAY,
          fontWeight: 800,
          color: '#F4F6F8',
          align: 'center',
          lineHeight: 0.95,
          letterSpacing: -2,
        },
        animation: { preset: 'scaleIn', trigger: 'scroll', duration: 1000 },
      },
      {
        id: id(),
        type: 'button',
        label: 'Publicar con PLIEGO',
        x: 400,
        y: 780,
        width: 400,
        height: 56,
        ...base(2),
        fill: '#4F80FF',
        textColor: '#FFFFFF',
        cornerRadius: 999,
        fontSize: 16,
        fontWeight: 700,
        fontFamily: FONT,
        interaction: { href: 'pliego:next', hoverScale: 1.06 },
        animation: { preset: 'fadeUp', delay: 180, trigger: 'scroll' },
        effects: {
          shadowColor: '#4F80FF',
          shadowBlur: 36,
          shadowOffsetY: 14,
          shadowOpacity: 0.45,
        },
      },
      {
        id: id(),
        type: 'text',
        x: 300,
        y: 900,
        width: 600,
        height: 40,
        ...base(3),
        text: 'Revista digital · link vivo · sin PDF plano',
        style: {
          fontSize: 14,
          fontFamily: MONO,
          fontWeight: 500,
          color: '#8B95A3',
          align: 'center',
          letterSpacing: 2,
        },
        animation: { preset: 'fadeIn', delay: 260, trigger: 'scroll' },
      },
    ]),
  ];
  doc.meta.width = w;
  doc.meta.height = h;
  doc.meta.templateId = 'revista-doble';
  doc.meta.templateName = 'Página de revista';
  return doc;
}

function buildCatalogo(): DocumentModel {
  const w = 1080;
  const h = 1350;
  const doc = createEmptyDocument('Catálogo', w, h);
  doc.pages = [
    page('Lookbook', 0, '#0B0E11', [
      {
        id: id(),
        type: 'shape',
        shape: 'ellipse',
        x: 560,
        y: -160,
        width: 700,
        height: 700,
        ...base(0),
        fill: '#A855F7',
        fillGradient: {
          type: 'radial',
          stops: [
            { offset: 0, color: '#FF4EDB' },
            { offset: 0.5, color: '#A855F7' },
            { offset: 1, color: '#0B0E11' },
          ],
        },
        opacity: 0.65,
        animation: { preset: 'scaleIn', duration: 1300, trigger: 'load' },
        effects: { blendMode: 'screen' },
      },
      {
        id: id(),
        type: 'text',
        x: 64,
        y: 72,
        width: 400,
        height: 32,
        ...base(1),
        text: 'LOOKBOOK  ·  SS26',
        style: {
          fontSize: 13,
          fontFamily: MONO,
          fontWeight: 600,
          color: '#A855F7',
          align: 'left',
          letterSpacing: 4,
        },
        animation: { preset: 'fadeIn', trigger: 'load' },
      },
      {
        id: id(),
        type: 'text',
        x: 64,
        y: 200,
        width: 920,
        height: 200,
        ...base(2),
        text: 'Objetos\ncon carácter',
        style: {
          fontSize: 88,
          fontFamily: DISPLAY,
          fontWeight: 800,
          color: '#F4F6F8',
          align: 'left',
          lineHeight: 0.95,
          letterSpacing: -3,
        },
        animation: { preset: 'fadeUp', trigger: 'load' },
      },
      {
        id: id(),
        type: 'shape',
        shape: 'rect',
        x: 64,
        y: 460,
        width: 72,
        height: 4,
        ...base(3),
        fill: '#B2FF3A',
        animation: { preset: 'slideLeft', delay: 140, trigger: 'load' },
      },
      {
        id: id(),
        type: 'text',
        x: 64,
        y: 500,
        width: 720,
        height: 80,
        ...base(4),
        text: 'Dos piezas. Un gesto. Un CTA que vende sin gritar.',
        style: {
          fontSize: 20,
          fontFamily: BODY,
          fontWeight: 400,
          color: '#B8C0CC',
          align: 'left',
          lineHeight: 1.4,
        },
        animation: { preset: 'fadeUp', delay: 180, trigger: 'load' },
      },
      {
        id: id(),
        type: 'shape',
        shape: 'rect',
        x: 64,
        y: 640,
        width: 440,
        height: 420,
        ...base(5),
        fill: '#121826',
        cornerRadius: 12,
        animation: { preset: 'fadeUp', trigger: 'load' },
        effects: { shadowBlur: 32, shadowOffsetY: 16, shadowOpacity: 0.3 },
      },
      {
        id: id(),
        type: 'shape',
        shape: 'rect',
        x: 540,
        y: 640,
        width: 440,
        height: 420,
        ...base(6),
        fill: '#4F80FF',
        fillGradient: {
          type: 'linear',
          angle: 160,
          stops: [
            { offset: 0, color: '#4F80FF' },
            { offset: 1, color: '#FF4EDB' },
          ],
        },
        cornerRadius: 12,
        animation: { preset: 'fadeUp', delay: 120, trigger: 'load' },
      },
      {
        id: id(),
        type: 'button',
        label: 'Ver la edit →',
        x: 64,
        y: 1180,
        width: 200,
        height: 52,
        ...base(7),
        fill: '#F4F6F8',
        textColor: '#0B0E11',
        cornerRadius: 999,
        fontSize: 15,
        fontWeight: 700,
        fontFamily: FONT,
        interaction: { href: 'pliego:next', hoverScale: 1.05 },
        animation: { preset: 'fadeUp', delay: 280, trigger: 'load' },
      },
    ]),
    page('Productos', 1, '#F7F5F0', [
      {
        id: id(),
        type: 'text',
        x: 64,
        y: 64,
        width: 400,
        height: 32,
        ...base(0),
        text: '02  —  LA EDIT',
        style: {
          fontSize: 13,
          fontFamily: MONO,
          fontWeight: 600,
          color: '#A855F7',
          align: 'left',
          letterSpacing: 3,
        },
        animation: { preset: 'fadeIn', trigger: 'scroll' },
      },
      {
        id: id(),
        type: 'text',
        x: 64,
        y: 120,
        width: 900,
        height: 100,
        ...base(1),
        text: 'Piezas seleccionadas',
        style: {
          fontSize: 52,
          fontFamily: 'Playfair Display',
          fontWeight: 700,
          color: '#111111',
          align: 'left',
        },
        animation: { preset: 'fadeUp', trigger: 'scroll' },
      },
      {
        id: id(),
        type: 'shape',
        shape: 'rect',
        x: 64,
        y: 280,
        width: 440,
        height: 560,
        ...base(2),
        fill: '#0B0E11',
        cornerRadius: 12,
        animation: { preset: 'fadeUp', trigger: 'scroll' },
        effects: { shadowBlur: 32, shadowOffsetY: 16, shadowOpacity: 0.25 },
      },
      {
        id: id(),
        type: 'text',
        x: 96,
        y: 700,
        width: 360,
        height: 80,
        ...base(3),
        text: '01  ·  Forma\nNegro absoluto',
        style: {
          fontSize: 22,
          fontFamily: FONT,
          fontWeight: 600,
          color: '#F4F6F8',
          align: 'left',
          lineHeight: 1.3,
        },
        animation: { preset: 'fadeUp', delay: 80, trigger: 'scroll' },
      },
      {
        id: id(),
        type: 'shape',
        shape: 'rect',
        x: 540,
        y: 280,
        width: 440,
        height: 560,
        ...base(4),
        fill: '#4F80FF',
        fillGradient: {
          type: 'linear',
          angle: 160,
          stops: [
            { offset: 0, color: '#4F80FF' },
            { offset: 1, color: '#FF4EDB' },
          ],
        },
        cornerRadius: 12,
        animation: { preset: 'fadeUp', delay: 120, trigger: 'scroll' },
      },
      {
        id: id(),
        type: 'text',
        x: 572,
        y: 700,
        width: 360,
        height: 80,
        ...base(5),
        text: '02  ·  Color\nGradiente vivo',
        style: {
          fontSize: 22,
          fontFamily: FONT,
          fontWeight: 600,
          color: '#F4F6F8',
          align: 'left',
          lineHeight: 1.3,
        },
        animation: { preset: 'fadeUp', delay: 160, trigger: 'scroll' },
      },
      {
        id: id(),
        type: 'text',
        x: 64,
        y: 900,
        width: 920,
        height: 120,
        ...base(6),
        text: 'Sustituye cada panel por producto real. Enlaza el botón a tu tienda o a la siguiente página. El lookbook digital vende con presencia, no con catálogo PDF.',
        style: {
          fontSize: 18,
          fontFamily: BODY,
          fontWeight: 400,
          color: '#4A5058',
          align: 'left',
          lineHeight: 1.5,
        },
        animation: { preset: 'fadeIn', delay: 100, trigger: 'scroll' },
      },
      {
        id: id(),
        type: 'button',
        label: 'Shop the edit',
        x: 64,
        y: 1180,
        width: 200,
        height: 48,
        ...base(7),
        fill: '#111111',
        textColor: '#FFFFFF',
        cornerRadius: 999,
        fontSize: 14,
        fontWeight: 700,
        fontFamily: FONT,
        interaction: { href: 'pliego:next', hoverScale: 1.05 },
        animation: { preset: 'fadeUp', trigger: 'scroll' },
      },
    ]),
    page('Cierre', 2, '#0B0E11', [
      {
        id: id(),
        type: 'shape',
        shape: 'ellipse',
        x: 200,
        y: 220,
        width: 680,
        height: 680,
        ...base(0),
        fill: '#FF4EDB',
        fillGradient: {
          type: 'radial',
          stops: [
            { offset: 0, color: '#FF4EDB' },
            { offset: 0.45, color: '#A855F7' },
            { offset: 1, color: '#0B0E11' },
          ],
        },
        opacity: 0.55,
        animation: { preset: 'scaleIn', trigger: 'scroll', duration: 1200 },
      },
      {
        id: id(),
        type: 'text',
        x: 80,
        y: 420,
        width: 920,
        height: 180,
        ...base(1),
        text: 'LA EDIT\nYA ESTÁ LISTA',
        style: {
          fontSize: 64,
          fontFamily: DISPLAY,
          fontWeight: 800,
          color: '#F4F6F8',
          align: 'center',
          lineHeight: 0.95,
          letterSpacing: -2,
        },
        animation: { preset: 'fadeUp', trigger: 'scroll' },
      },
      {
        id: id(),
        type: 'button',
        label: 'Publicar lookbook',
        x: 300,
        y: 700,
        width: 480,
        height: 56,
        ...base(2),
        fill: '#F4F6F8',
        textColor: '#0B0E11',
        cornerRadius: 999,
        fontSize: 16,
        fontWeight: 700,
        fontFamily: FONT,
        interaction: { href: 'pliego:next', hoverScale: 1.06 },
        animation: { preset: 'fadeUp', delay: 160, trigger: 'scroll' },
        effects: { shadowBlur: 32, shadowOffsetY: 14, shadowOpacity: 0.4 },
      },
      {
        id: id(),
        type: 'text',
        x: 240,
        y: 800,
        width: 600,
        height: 40,
        ...base(3),
        text: 'PLIEGO  ·  lookbook digital interactivo',
        style: {
          fontSize: 13,
          fontFamily: MONO,
          fontWeight: 500,
          color: '#8B95A3',
          align: 'center',
          letterSpacing: 2,
        },
        animation: { preset: 'fadeIn', delay: 240, trigger: 'scroll' },
      },
    ]),
  ];
  doc.meta.width = w;
  doc.meta.height = h;
  doc.meta.templateId = 'catalogo-producto';
  doc.meta.templateName = 'Catálogo / lookbook';
  return doc;
}


function buildPresentacion(): DocumentModel {
  const w = 1920;
  const h = 1080;
  const doc = createEmptyDocument('Presentación', w, h);
  doc.pages = [
    page('Apertura', 0, '#050608', [
      {
        id: id(),
        type: 'shape',
        shape: 'ellipse',
        x: 1180,
        y: -160,
        width: 980,
        height: 980,
        ...base(0),
        fill: '#A855F7',
        opacity: 0.5,
        fillGradient: {
          type: 'radial',
          stops: [
            { offset: 0, color: '#FF4EDB' },
            { offset: 0.45, color: '#4F80FF' },
            { offset: 1, color: '#050608' },
          ],
        },
        animation: { preset: 'scaleIn', trigger: 'load', duration: 1400 },
        effects: { blendMode: 'screen' },
      },
      {
        id: id(),
        type: 'text',
        x: 120,
        y: 120,
        width: 640,
        height: 36,
        ...base(1),
        text: 'PLIEGO  ·  SLIDE 01  ·  KEYNOTE',
        style: {
          fontSize: 14,
          fontFamily: MONO,
          fontWeight: 600,
          color: '#8B95A3',
          align: 'left',
          letterSpacing: 4,
        },
        animation: { preset: 'fadeIn', trigger: 'load' },
      },
      {
        id: id(),
        type: 'text',
        x: 120,
        y: 280,
        width: 1400,
        height: 260,
        ...base(2),
        text: 'Pitch con\npresencia',
        style: {
          fontSize: 108,
          fontFamily: DISPLAY,
          fontWeight: 800,
          color: '#F4F6F8',
          align: 'left',
          lineHeight: 0.92,
          letterSpacing: -4,
        },
        animation: { preset: 'fadeUp', trigger: 'load' },
      },
      {
        id: id(),
        type: 'shape',
        shape: 'rect',
        x: 120,
        y: 580,
        width: 88,
        height: 5,
        ...base(3),
        fill: '#B2FF3A',
        animation: { preset: 'slideLeft', delay: 160, trigger: 'load' },
      },
      {
        id: id(),
        type: 'text',
        x: 120,
        y: 620,
        width: 720,
        height: 80,
        ...base(4),
        text: 'Widescreen, motion y un cierre que pide acción.\nUna idea. Una diapositiva. Un golpe.',
        style: {
          fontSize: 22,
          fontFamily: BODY,
          fontWeight: 400,
          color: '#B8C0CC',
          align: 'left',
          lineHeight: 1.4,
        },
        animation: { preset: 'fadeUp', delay: 200, trigger: 'load' },
      },
      {
        id: id(),
        type: 'button',
        label: 'Siguiente idea →',
        x: 120,
        y: 820,
        width: 240,
        height: 56,
        ...base(5),
        fill: '#F4F6F8',
        textColor: '#050608',
        cornerRadius: 999,
        fontSize: 16,
        fontWeight: 700,
        fontFamily: FONT,
        interaction: { href: 'pliego:next', hoverScale: 1.05 },
        animation: { preset: 'fadeUp', delay: 280, trigger: 'load' },
      },
    ]),
    page('Argumento', 1, '#0B0E11', [
      {
        id: id(),
        type: 'shape',
        shape: 'rect',
        x: 0,
        y: 0,
        width: 640,
        height: 1080,
        ...base(0),
        fill: '#121826',
      },
      {
        id: id(),
        type: 'text',
        x: 80,
        y: 100,
        width: 480,
        height: 32,
        ...base(1),
        text: '02  —  EL ARGUMENTO',
        style: {
          fontSize: 13,
          fontFamily: MONO,
          fontWeight: 600,
          color: '#4F80FF',
          align: 'left',
          letterSpacing: 3,
        },
        animation: { preset: 'fadeIn', trigger: 'scroll' },
      },
      {
        id: id(),
        type: 'text',
        x: 80,
        y: 180,
        width: 480,
        height: 280,
        ...base(2),
        text: 'Tres ideas.\nCero ruido.\nMáximo impacto.',
        style: {
          fontSize: 56,
          fontFamily: DISPLAY,
          fontWeight: 800,
          color: '#F4F6F8',
          align: 'left',
          lineHeight: 1.05,
          letterSpacing: -2,
        },
        animation: { preset: 'fadeUp', trigger: 'scroll' },
      },
      {
        id: id(),
        type: 'text',
        x: 80,
        y: 520,
        width: 460,
        height: 240,
        ...base(3),
        text: 'Cada slide es una portada: tipografía display, un acento neón y un CTA que mueve la conversación. No rellenes — edita.',
        style: {
          fontSize: 20,
          fontFamily: BODY,
          fontWeight: 400,
          color: '#8B95A3',
          align: 'left',
          lineHeight: 1.5,
        },
        animation: { preset: 'fadeIn', delay: 120, trigger: 'scroll' },
      },
      {
        id: id(),
        type: 'text',
        x: 760,
        y: 200,
        width: 1000,
        height: 120,
        ...base(4),
        text: '01  Problema claro',
        style: {
          fontSize: 42,
          fontFamily: FONT,
          fontWeight: 700,
          color: '#F4F6F8',
          align: 'left',
        },
        animation: { preset: 'slideLeft', trigger: 'scroll' },
      },
      {
        id: id(),
        type: 'text',
        x: 760,
        y: 360,
        width: 1000,
        height: 120,
        ...base(5),
        text: '02  Solución memorable',
        style: {
          fontSize: 42,
          fontFamily: FONT,
          fontWeight: 700,
          color: '#F4F6F8',
          align: 'left',
        },
        animation: { preset: 'slideLeft', delay: 100, trigger: 'scroll' },
      },
      {
        id: id(),
        type: 'text',
        x: 760,
        y: 520,
        width: 1000,
        height: 120,
        ...base(6),
        text: '03  Próximo paso',
        style: {
          fontSize: 42,
          fontFamily: FONT,
          fontWeight: 700,
          color: '#B2FF3A',
          align: 'left',
        },
        animation: { preset: 'slideLeft', delay: 200, trigger: 'scroll' },
      },
      {
        id: id(),
        type: 'button',
        label: 'Ir al cierre →',
        x: 760,
        y: 820,
        width: 220,
        height: 52,
        ...base(7),
        fill: '#4F80FF',
        textColor: '#FFFFFF',
        cornerRadius: 999,
        fontSize: 15,
        fontWeight: 600,
        interaction: { href: 'pliego:next', hoverScale: 1.05 },
        animation: { preset: 'fadeUp', delay: 280, trigger: 'scroll' },
      },
    ]),
    page('Cierre', 2, '#050608', [
      {
        id: id(),
        type: 'shape',
        shape: 'rect',
        x: 0,
        y: 0,
        width: 1920,
        height: 1080,
        ...base(0),
        fill: '#050608',
        fillGradient: {
          type: 'linear',
          angle: 135,
          stops: [
            { offset: 0, color: '#050608' },
            { offset: 0.5, color: '#121826' },
            { offset: 1, color: '#1a1030' },
          ],
        },
      },
      {
        id: id(),
        type: 'text',
        x: 160,
        y: 300,
        width: 1600,
        height: 200,
        ...base(1),
        text: '¿Hablamos?',
        style: {
          fontSize: 110,
          fontFamily: DISPLAY,
          fontWeight: 800,
          color: '#F4F6F8',
          align: 'center',
          letterSpacing: -4,
        },
        animation: { preset: 'scaleIn', trigger: 'scroll', duration: 1000 },
      },
      {
        id: id(),
        type: 'text',
        x: 420,
        y: 540,
        width: 1080,
        height: 60,
        ...base(2),
        text: 'Publica esta deck. Comparte el link. Cierra la reunión.',
        style: {
          fontSize: 24,
          fontFamily: BODY,
          fontWeight: 400,
          color: '#8B95A3',
          align: 'center',
        },
        animation: { preset: 'fadeUp', delay: 120, trigger: 'scroll' },
      },
      {
        id: id(),
        type: 'button',
        label: 'Empezar en PLIEGO',
        x: 760,
        y: 680,
        width: 400,
        height: 60,
        ...base(3),
        fill: '#B2FF3A',
        textColor: '#050608',
        cornerRadius: 999,
        fontSize: 18,
        fontWeight: 700,
        fontFamily: FONT,
        interaction: { href: 'pliego:next', hoverScale: 1.06 },
        animation: { preset: 'fadeUp', delay: 220, trigger: 'scroll' },
        effects: { shadowBlur: 36, shadowOffsetY: 14, shadowOpacity: 0.4 },
      },
    ]),
  ];
  doc.meta.width = w;
  doc.meta.height = h;
  doc.meta.templateId = 'presentacion-slide';
  doc.meta.templateName = 'Presentación slide';
  return doc;
}

export const templates: TemplateDef[] = [
  {
    id: 'manifesto-digital',
    name: 'Manifiesto digital',
    category: 'editorial',
    description: '3 actos: portada neón, ensayo tipográfico y cierre con CTA.',
    width: 1440,
    height: 900,
    orientation: 'landscape',
    build: buildManifestoDigital,
  },
  {
    id: 'portfolio-kinetic',
    name: 'Portfolio kinetic',
    category: 'editorial',
    description: 'Hero tipográfico, case study animado y cierre publicable.',
    width: 1080,
    height: 1350,
    orientation: 'portrait',
    build: buildPortfolioKinetic,
  },
  {
    id: 'portada-editorial',
    name: 'Portada editorial',
    category: 'portada',
    description: 'Cover PLIEGO + cuerpo editorial interactivo + cierre.',
    width: 1080,
    height: 1350,
    orientation: 'portrait',
    build: buildPortadaEditorial,
  },
  {
    id: 'revista-doble',
    name: 'Página de revista',
    category: 'revista',
    description: 'Portada, ensayo a dos columnas y cierre con motion.',
    width: 1200,
    height: 1600,
    orientation: 'portrait',
    build: buildRevista,
  },
  {
    id: 'catalogo-producto',
    name: 'Catálogo / lookbook',
    category: 'catalogo',
    description: 'Lookbook SS26: hero, edit dual y cierre shoppable.',
    width: 1080,
    height: 1350,
    orientation: 'portrait',
    build: buildCatalogo,
  },
  {
    id: 'presentacion-slide',
    name: 'Presentación slide',
    category: 'presentacion',
    description: 'Apertura, argumento y cierre widescreen con CTAs.',
    width: 1920,
    height: 1080,
    orientation: 'landscape',
    build: buildPresentacion,
  },
];

export function getTemplate(id: string) {
  return templates.find((t) => t.id === id);
}

export function listTemplates() {
  return templates.map(({ build: _b, ...meta }) => meta);
}
